### ISSUE TITLE
[8] Als Entwickler moechte ich ueber Moeglichkeiten zum Musik-Fingerprinting bescheid wissen.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#11]
... um qualifiziert entscheiden zu koennen, welche technischen Moeglichkeiten im weiteren Projektverlauf verfolgt werden.
- [ ] How to generate the fingerprint in the browser?
- [x] Welche Datenbanken gibt es?
  - [x] LibreFM?!
  - [ ] Musicbrainz?!
- [x] API ansteuerbar? Alle mit API Keys?
  - [x] Anforderungen fuer API Key?
- [x] Gibt es Libraries dafuer?

**Comment by Brotonyum** [comment]
Wie wird das Ergebnis festgehalten? Beitrag?

**Comment by perguth** [comment]
@Brotonyum Ergebnisse aus "Als Entwickler..." Tickets sollen unter https://github.com/peermusic/research in Markdown Dokumenten erfasst werden. Wir hatten das im Team kurz telefonisch besprochen.

**Comment by perguth** [comment]
Please consolidate findings here: https://github.com/peermusic/research/blob/master/music-recognition.md
