### ISSUE TITLE
[5] Als Nutzer moechte ich mir meinen Musikbestand anzeigen lassen koennen.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#12]
... um einen Ueberblick ueber meine Musik zu erhalten.
- [x] Musik aus der Datenbank als Liste aufbereiten. Grafisch darstellen.

**Comment by Brotonyum** [comment]
Story: Als Nutzer möchte ich mir meinen Musikbestand anzeigen lassen können, damit ich weiß welche Lieder noch abgespielt werden.
Beschreibung: Erstellung einer Musikliste, die die Musikstücke anzeigt, die noch abgespielt werden.

**Comment by queicherius** [comment]
I basically did that already in https://github.com/peermusic/player-engine/tree/master/example while completing the other user stories. Should we just move this into the desktop repository and add some more pretty styling or does this count as completed?

**Comment by perguth** [comment]
@queicherius :+1:

**Comment by perguth** [comment]
Implemented in https://github.com/peermusic/desktop
