### ISSUE TITLE
[3] Als Nutzer moechte ich Titel aus meinem Musikbestand entfernen koennen.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#13]
... um unerwuenschte Titel entfernen zu koennen.
- [x] Click -> remove from UI and storage.

**Comment by Brotonyum** [comment]
Bitte übernehmen:
Story: Als Nutzer möchte ich Titel aus meinem Musikbestand entfernen können, damit ich unerwünschte Lieder löschen kann.
Beschreibung:Erstellung einer Entfernen-Funktion, die es ermöglicht Lieder auf der Liste zu entfernen.

**Comment by perguth** [comment]
There is a bug in our current implementation which makes removed tracks reappear: peermusic/desktop/issues/1
