### ISSUE TITLE
[4] Als Nutzer moechte ich in meinem Musikbestand Musik zum Abspielen auswaehlen koennen.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#14]
... um sie anhoeren zu koennen.
- [x] Click -> Play

**Comment by Brotonyum** [comment]
Bitte anpassen:
Beschreibung: Durch das Anklicken eines Titels in der Liste, wird dieses Lied abgespielt.

**Comment by perguth** [comment]
Implemented in https://github.com/peermusic/desktop
