### ISSUE TITLE
[16] Als Entwickler moechte ich einen Ueberblick ueber technische Moeglichkeiten zur Vernetzung haben.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#16]
... um qualifiziert entscheiden zu koennen, wie die Daten getauscht werden sollen.

Informationen sollen vorliegen fuer folgende Bereiche:
- [ ] Sharing
  - [ ] Tracker within the browser?!
- [ ] Authenticating
- [ ] Distributed DBs

**Comment by queicherius** [comment]
Can we get a little document about this [here](https://github.com/peermusic/research)? :)
