### ISSUE TITLE
As a user I want to have a streamlined user interface to ease interaction. [3]

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#18]
- [x] Add folders drag n drop (optional)
- [x] Only one button that allows to pick files and folders or else two.

Integrate in https://github.com/peermusic/desktop

**Comment by queicherius** [comment]
Support for drag & drop directories: peermusic/desktop@6fb6801f75abf12cef51f45e2388869b390c00d1

**Comment by queicherius** [comment]
A single button for both files and directories is not possible: [Chromium Bug Report](https://code.google.com/p/chromium/issues/detail?id=59818)

> Marking as Won't Fix since there is no workable solution for Linux/Win.
