### ISSUE TITLE
[4] Als Entwickler moechte ich ueber client-seitige Datenbanken (Desktop) bescheid wissen.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#2]
... um qualifiziert entscheiden zu koennen, welche Technologie wir einsetzen.
- [x] Es soll geklaert werden, welche Moeglichkeiten zum Ablegen groesserer Datenmengen im Browser  auf dem Desktop bestehen.

**Comment by Brotonyum** [comment]
Wollt ihr die Ergebnisse in einem Beitrag festhalten?

**Comment by perguth** [comment]
@queicherius Could you look over https://github.com/peermusic/research/blob/master/storage.md before we close this?

**Comment by perguth** [comment]
Our discussion went into the direction of sticking with `FileSystem` even though it's a Chrome/Chromium only solution. We should add some of our reasons to the markdown doc.
