### ISSUE TITLE
As a dev I want to handle music file metadata to utilize it for the inferface. [7]

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#20]
- [x] Save original music file name
- [x] Parse/save ID3 tags
- [x] Parse/save filename (take exemplary file name formats from CD rippers)
- [x] Write a independent module
- [x] Save locally see #17 

Resulting module should be used in https://github.com/peermusic/desktop

**Comment by perguth** [comment]
@queicherius I cannot verify:
- [x] Save original music file name

**Comment by queicherius** [comment]
Looks good now?

**Comment by perguth** [comment]
Good :+1:
