### ISSUE TITLE
As a dev I want to have a NodeJS scraping server that delivers matching information for music tracks. [12]

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#21]
- [x] logic tweaks

From the old US:
- [x] Scrap Last.FM
- [x] Provide a REST-API so browser instances can request information
  - [x] Cover Art
  - [x] Information about similarity
- [x] Scrape on API call request
- [x] Save collected information locally on the server for later requests

Write relevant modules and combine it here: https://github.com/peermusic/node-scraping-server

**Comment by perguth** [comment]
Maybe this can come in handy: https://github.com/restify/node-restify

**Comment by queicherius** [comment]
See peermusic/scrape-engine#2 & peermusic/scrape-engine#3
