### ISSUE TITLE
As a user I want to decide who can access my NodeJS scraping server to have control. [6]

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#22]
- [x] Shared private sign key (tweetnacl)

From the previous sprint:
- [x] To allow users to connect I create a one-time URL for them (some form of pub/priv key information exchange)
- [x] Free text can be associated with the access that has been granted through a URL so the user can add additional information about the person that got access
- [x] The user interface is command line based

Integrate (maybe via modules) into https://github.com/peermusic/node-scraping-server

**Comment by queicherius** [comment]
Please review the [messaging module](https://github.com/peermusic/secure-client-server-messaging), the [scraping server](https://github.com/peermusic/node-scraping-server) and the [UI](https://github.com/peermusic/desktop/tree/feature/user-interface).
