### ISSUE TITLE
As a user I want to have a radio functionality to automatically create good playlists. [9]

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#25]
- [x] get similarity information
- [x] check if music is available for playback
- [x] further broaden -> repeat (n-times)
- [x] if fail -> good guess (same album -> same artist -> just random)
  - [x] check history to avoid close loops

Writing modules integrate into https://github.com/peermusic/desktop

**Comment by queicherius** [comment]
Implement here: https://github.com/peermusic/desktop/blob/feature/user-interface/app/actions/player.js#L298

**Comment by ryomiyaichi** [comment]
@queicherius: https://github.com/peermusic/music-similarity

**Comment by queicherius** [comment]
Encrypted requests are done peermusic/music-similarity@4cbe40ad8389aad455df2422866f5bb1f6c6d50c

**Comment by ryomiyaichi** [comment]
Added fallback if there aren't any similar tracks available: peermusic/desktop@2b7ad84fe12d594f78c37bf7fb6eddaaa490fa7b

**Comment by queicherius** [comment]
:+1:
