### ISSUE TITLE
[6] Als Entwickler moechte ich ueber client-seitige Datenbanken (Android) bescheid wissen.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#3]
... um die Grundlage fuer die weitere Enticklung zu legen.
- [ ] Es soll geklaert werden, welche Moeglichkeiten zum Ablegen groesserer Datenmengen im Browser in Android bestehen.

**Comment by Brotonyum** [comment]
Wollt ihr die Ergebnisse in einem Beitrag festhalten?

**Comment by perguth** [comment]
This issue will be answered together with #2
