### ISSUE TITLE
As a User I want to have a good looking UI. [20]

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#32]
- [x] Setup the new development workflow
- [x] Design a good looking UI with a dark color scheme around the already existing functionality
- [x] Show a drop area on drag & drop
- [x] Figure out if we want to use React for this instead of writing HTML to the DOM ourselves
- [x] Rewrite in Redux & React
- [x] Create a structure that allows for HTML5 hashlinks for each page, so the browser's back/forward button work
- [x] Create individual pages:
  - [x] Songs
  - [x] Albums
  - [x] Artists
  - [x] Playing next
  - [x] Manage friends
  - [x] Manage songs (files / delete single songs)
  - [x] Manage servers
  - [x] Downloads
- [x] Missing functionality from rewrites
  - [x] History + playing next
  - [x] Cover Art
- [x] Add the ability to play tracks non-random (e.g. all tracks of an album)
- [x] Crosslink between the pages (in songlists and in player current song)
  - [x] Albums
  - [x] Artists
- [x] Play all buttons
- [x] Search functionality
- [x] Save song duration when music files get added
- [x] Show status of songs (local, downloading, via friends)
- [x] Favorite functionality

**Comment by queicherius** [comment]
Progress can be found in https://github.com/peermusic/desktop/tree/feature/user-interface

**Comment by queicherius** [comment]
Alright. If someone wants to look through [filesystem](https://github.com/peermusic/file-system/tree/chore/slim-filesystem), [subfolders-too](https://github.com/peermusic/subfolders-too), [player-engine](https://github.com/peermusic/player-engine/tree/chore/slim-engine) and [desktop](https://github.com/peermusic/desktop/tree/feature/user-interface) and give the ok for the review, then I will merge the stuff together and move it to done.

**Comment by perguth** [comment]
Code worked for @ryomiyaichi, -> closing.
