### ISSUE TITLE
[3] Als Entwickler moechte ich pruefen, ob eine Musikdatei im richtigen Format vorliegt.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#4]
... um nicht versehentlich unpassende Dateien hinzuzufuegen.
- [ ] Welche Musikformate werden per Default unterstuetzt?
- [x] Es soll eine rudimentaere Pruefung erfolgen, ob die durch den Nutzer im Browser abgelegten Musikdateien in abspielbaren Formaten vorliegen.

**Comment by Brotonyum** [comment]
Welche Musikformate wollt ihr alle unterstützen? Das dann in der Beschreibung festlegen weil sonst wird es schwer die US auf Done zu setzen ;)

**Comment by ryomiyaichi** [comment]
For now we only support mp3 files. There is the option to support WAV and OGG if needed.

**Comment by ryomiyaichi** [comment]
Added support for WAV and OGG

**Comment by queicherius** [comment]
You could change that around, that the FileStorage gets an array of allowed file types in the constructor. Makes it more reusable.

**Comment by queicherius** [comment]
Completed with peermusic/file-system@4d11e2fec4b0007d1764f648c9412df37a7b5658
