### ISSUE TITLE
Release to gh-pages [0]

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#48]
- public folder after `gulp`

**Comment by pguth** [comment]
First temporary to `gh-pages` in repo https://github.com/peermusic/desktop then finally to https://github.com/peermusic/peermusic.github.io

**Comment by perguth** [comment]
First temporary to gh-pages in repo https://github.com/peermusic/desktop then finally to https://github.com/peermusic/peermusic.github.io
