### ISSUE TITLE
set and exchange sharing levels

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#57]
See: peermusic/app/pull/24

**Comment by pguth** [comment]
Solved in #41

**Comment by perguth** [comment]
@queicherius Could you sweeten the option field up graphically?

**Comment by queicherius** [comment]
:+1:

**Comment by perguth** [comment]
<strike>I would keep this ticket around for the functionality (added new checkboxes in the opening post).</strike> It seemed to big for one ticket, now only for adding/exchanging.
