### ISSUE TITLE
appcache file

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#59]
We should get this automatically via #60.

**Comment by perguth** [comment]
Code is here: peermusic/app/pull/13

But MDN writes:

> Deprecated
> This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. 

Is hyperboot actually relying on this?!

**Comment by perguth** [comment]
[MDN: Using Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers):

> The previous attempt — **_AppCache**_ — seemed to be a good idea because it allowed you to specify assets to cache really easily. However, it made many assumptions about what you were trying to do and then broke horribly when your app didn’t follow those assumptions exactly. Read Jake Archibald's Application Cache is a Douchebag for more details. ...
> 
> Using a Service Worker you can easily set an app up to use cached assets first, thus providing a default experience even when offline, before then getting more data from the network (commonly known as Offline First). This is already available with native apps, which is one of the main reasons native apps are often chosen over web apps.

Services Workers as such are partially support for Desktop and Android: [caniuse.com](http://caniuse.com/#search=Service%20Workers)

**Comment by queicherius** [comment]
I saw the deprecated warning as well when I dabbled around with it. I think hyperboot doesn't use it, at least I didnt see it used anywhere.

**Comment by perguth** [comment]
He still does: view-source:http://demo.hyperboot.org/ I asked him on IRC about his thoughts on this a few minutes ago - let's see.

**Comment by queicherius** [comment]
Reference: peermusic/app#13

**Comment by perguth** [comment]
Google still recommends the appcache file:

> Use AppCache to ensure that your app works or presents the user with an experience when they are offline.

https://developer.chrome.com/multidevice/android/installtohomescreen
