### ISSUE TITLE
[10] Als Nutzer moechte Musik abspielen lassen und pausieren koennen.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#6]
... um grundlegende Musik-Player Funktionalitaet zur Verfuegugung zu haben.
- [x] Musik aus der clientseitigen Datenbank ueber HTML5 player starten
- [x] ... pausieren.

**Comment by perguth** [comment]
We could stick to/copy the following API from https://github.com/zohararad/audio5js#api Here are the parts I found useful:

### Instance Methods
- **load** - load an audio file from URL
- **play** - play loaded audio
- **pause** - pause loaded audio
- **playPause** - toggle play/pause playback state
- **volume** - get / set volume (volume range is 0-1)
- **seek** - move playhead position to a given time in seconds

### Instance Attributes
- **playing** - boolean flag indicating whether audio is playing (true) or paused (false).
- **duration** - audio duration in seconds.
- **position** - audio playhead position in seconds.

**Comment by perguth** [comment]
My idea was to have a [`music-player-engine`](https://github.com/peermusic/music-player-engine) so we can decouple the UI from actual functionality.

So the UI would currently be just exemplary and living under `examples/` there. Thoughts?

**Comment by queicherius** [comment]
:+1: That API looks good. 

I'd keep the UI under examples until we start with the actual UI part.

**Comment by perguth** [comment]
Maybe push that a bit into the direction of our playlist feature:

### Instance Methods
- **playing** - return audio identifier or if not playing `null`
- **playlist** - get / set the array of songs to be played
- **append** - append a track to the playlist
- **play** - play playlist audio if no argument given else play track given in argument
- **pause** - pause audio
- **toggle** - toggle play/pause playback state
- **volume** - get / set volume (volume range is 0-1)
- **seek** - move playhead position to a given time in seconds

### Instance Attributes
- **duration** - audio duration in seconds.
- **position** - audio playhead position in seconds.

### Instance Events
- **change** - notifies when the track changes
- **progress** - playhead position, emitted every second of playback

**Comment by perguth** [comment]
@queicherius What do you think?

**Comment by queicherius** [comment]
I like it.

Only thing I am thinking about is that I am not sure if it is a good idea to couple the audio API and the playlist functionality together so tightly. Then again they _are_ very similar things.

**Comment by perguth** [comment]
Having it outside would add the additional strain to react in time, right?

Only having a simple get/set for playlist would keep the main logic outside of the engine.

**Comment by queicherius** [comment]
On second thought - let's keep it inside. Should be easier to manage, as you say.

**Comment by perguth** [comment]
Implemented in https://github.com/peermusic/player-engine
Used in https://github.com/peermusic/desktop
