### ISSUE TITLE
notify developer when gulp build failed

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#65]

**Comment by queicherius** [comment]
peermusic/desktop@d753adb44015094a1bc908588bad177f2dcc7b54

**Comment by perguth** [comment]
:+1: on linux.

@ryomiyaichi: "Windows: >= 8, task bar balloon if earlier or Growl if that is installed."

Testable by eg adding the following while gulp is running:

``` js
// this will cause an gulp error since it's not in our dependencies
var cuid = require('cuid')
console.log(cuid())
```

**Comment by queicherius** [comment]
Works for me on Windows 7 (even with real notifications and no growl) and Mac OS X El Capitan

**Comment by perguth** [comment]
Nice!
