### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#68]
And the winner is:

![logo-final](https://cloud.githubusercontent.com/assets/4615516/12270905/c5152fd4-b958-11e5-889e-55748ec4186f.png)

Thanks! @queicherius @ryomiyaichi @Brotonyum

**Comment by queicherius** [comment]
How about one of these? Is the cloud recognizable?
1. ![6](https://cloud.githubusercontent.com/assets/4615516/12216514/1a483152-b6e5-11e5-858c-1b260b596176.png)
2. ![3](https://cloud.githubusercontent.com/assets/4615516/12216515/1a49710c-b6e5-11e5-9a5f-363fc63f2a97.png)
3. ![4](https://cloud.githubusercontent.com/assets/4615516/12216517/1a4b91da-b6e5-11e5-8156-2a7f1485ed50.png)
4. ![5](https://cloud.githubusercontent.com/assets/4615516/12216518/1a4be2ac-b6e5-11e5-9575-33387d6ddcc3.png)
5. ![b_2](https://cloud.githubusercontent.com/assets/4615516/12216565/6f7fb716-b6e6-11e5-956d-648918a6a0c7.png)
6. ![b_1](https://cloud.githubusercontent.com/assets/4615516/12216562/6f7dd734-b6e6-11e5-9768-32af434f3b4e.png)
7. ![b_3](https://cloud.githubusercontent.com/assets/4615516/12216564/6f7f55fa-b6e6-11e5-8557-b0358162e036.png)
8. ![b_4](https://cloud.githubusercontent.com/assets/4615516/12216563/6f7f2436-b6e6-11e5-8925-025bbee3d477.png)

**Comment by perguth** [comment]
:+1: I am with **4**!

I would like to see a version with a more simplistic music associated shape (eg. even just a ":musical_note:") in contrast.

**Comment by ryomiyaichi** [comment]
I am with 2, but would rather have an symbol like Per suggested instead of the clef.

**Comment by queicherius** [comment]
Some more quick & dirty one's.

![1](https://cloud.githubusercontent.com/assets/4615516/12222613/9d66c012-b7c1-11e5-876f-7ac61cda9ac7.png)
![2](https://cloud.githubusercontent.com/assets/4615516/12222614/9d67162a-b7c1-11e5-8ce3-ad1c692d1311.png)
![3](https://cloud.githubusercontent.com/assets/4615516/12222616/9d67aa72-b7c1-11e5-9822-923477b421eb.png)
![5](https://cloud.githubusercontent.com/assets/4615516/12222617/9d68ee0a-b7c1-11e5-96d2-a135f9069c06.png)
![6](https://cloud.githubusercontent.com/assets/4615516/12222618/9d6a1afa-b7c1-11e5-81a7-80ae472a58e9.png)
![7](https://cloud.githubusercontent.com/assets/4615516/12222615/9d678420-b7c1-11e5-8aaa-5a9ac2014f2c.png)

**Comment by perguth** [comment]
I would pick 1 and 4. Maybe add the cloud in?

**Comment by ryomiyaichi** [comment]
Those with the shading look neat :) If we could get the cloud in that would be awesome

**Comment by Brotonyum** [comment]
I would pick 4 as well ;)

**Comment by queicherius** [comment]
![2](https://cloud.githubusercontent.com/assets/4615516/12263329/72fc3348-b92e-11e5-8db3-44bfda7ec16b.png)
![1](https://cloud.githubusercontent.com/assets/4615516/12263330/7300eae6-b92e-11e5-8cc1-ff3781e65f5b.png)

(I would vote for the first one)

**Comment by ryomiyaichi** [comment]
1.

**Comment by perguth** [comment]
1. =)

**Comment by queicherius** [comment]
Alright. Going to do a full-resolution version of that then.

**Comment by perguth** [comment]
I wonder how it would look with a black note on orange background... maybe one last round?

**Comment by queicherius** [comment]
![aaaa](https://cloud.githubusercontent.com/assets/4615516/12264725/f4bc738e-b938-11e5-9fd9-956a9caf5f04.png)

![bbb](https://cloud.githubusercontent.com/assets/4615516/12264742/0b93b360-b939-11e5-9f68-9249eda84f8c.png)

**Comment by perguth** [comment]
Maybe turn the shadow into nyan-cat-rainbow awesomness!?!? D:
![nyancat](https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/Nyan_cat_250px_frame.PNG/220px-Nyan_cat_250px_frame.PNG)

**Comment by queicherius** [comment]
Nyan nyan nyan nyan :rainbow:

![4](https://cloud.githubusercontent.com/assets/4615516/12265194/113b7fac-b93c-11e5-9c88-45086daa8887.png)
![1](https://cloud.githubusercontent.com/assets/4615516/12265193/113b7458-b93c-11e5-9e2a-42c7a0416dd8.png)
![2](https://cloud.githubusercontent.com/assets/4615516/12265195/113c3668-b93c-11e5-9b09-6cd522b92eb0.png)
![3](https://cloud.githubusercontent.com/assets/4615516/12265196/113d3b08-b93c-11e5-96be-565974f1ebc2.png)
![5](https://cloud.githubusercontent.com/assets/4615516/12265271/751819f4-b93c-11e5-9720-e9916f3a41e8.png)

**Comment by queicherius** [comment]
![flyyy](https://cloud.githubusercontent.com/assets/4615516/12266854/a777af8c-b945-11e5-8de8-d6006071a263.png)

@pguth

**Comment by perguth** [comment]
1. ![1](https://cloud.githubusercontent.com/assets/4615516/12264725/f4bc738e-b938-11e5-9fd9-956a9caf5f04.png)
2. ![2](https://cloud.githubusercontent.com/assets/4615516/12264742/0b93b360-b939-11e5-9f68-9249eda84f8c.png) C
3. ![3](https://cloud.githubusercontent.com/assets/4615516/12265195/113c3668-b93c-11e5-9b09-6cd522b92eb0.png) P T
4. ![4](https://cloud.githubusercontent.com/assets/4615516/12263329/72fc3348-b92e-11e5-8db3-44bfda7ec16b.png)

**Comment by queicherius** [comment]
![logo-final](https://cloud.githubusercontent.com/assets/4615516/12270905/c5152fd4-b958-11e5-889e-55748ec4186f.png)

:cake:

**Comment by perguth** [comment]
We have a logo!  :fireworks: :fireworks: :fireworks:

**Comment by queicherius** [comment]
https://github.com/peermusic/app/blob/master/assets/logo.svg Clean version
