### ISSUE TITLE
subdivide `servers`

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#73]
...into
- hubs
- scraping servers

I would very much welcome that, as their both qualify as servers and I would like to have a table to put the hubs anyway  :grin:

The other way would be to automatically remove hubs when their no longer referenced by active whitelist entries but I would rather have the "techy" menu for that... we have a _nerdy_ process of contact establishment anyway, we not stick to that paradigm?!

**Comment by queicherius** [comment]
:+1: We can just add another horizontal menu for that.
