### ISSUE TITLE
big "add songs" logo in center when the player lacks songs

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#74]
Make it more obvious. User tests in class showed that people don't read the text and are confused  :satisfied:

**Comment by queicherius** [comment]
On which pages would that be? Songs / Albums / Artists / Manage songs?

**Comment by perguth** [comment]
Right after the "agree" step, when there are no songs added yet.

**Comment by perguth** [comment]
Asset `import-songs.png` missing.

**Comment by queicherius** [comment]
For some reason my IDE really doesn't like the `assets/`folder. peermusic/app@7a490edb09013ac63fe5dc105f15f60a51e16d4e

**Comment by perguth** [comment]
x)
