### ISSUE TITLE
piwik

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#76]
I would like to put a privacy preserving piwik tracking-_image_ into it. We have the data on Github anyway but behind their UI. Any thoughts?

**Comment by queicherius** [comment]
:+1: Analytics is cool.

**Comment by perguth** [comment]
Tracking code and user with access rights for our group created. I will pass the data around via Signal.

```
<!-- Piwik Image Tracker-->
<img src="https://analytics.guth.so/fair-tracking.php?idsite=32&rec=1" style="border:0" alt="" />
<!-- End Piwik -->
```
