### ISSUE TITLE
change color of playlist slide-in

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#77]
Looking at the screenshot I thought that a inverted colorscheme in the slide-in could be nice.

![peermusic 0.2](https://cdn.pbrd.co/images/GdA8qOn.png)

**Comment by queicherius** [comment]
Oh, you mean give the "playing next" also the lighter gray background?

**Comment by perguth** [comment]
We could also do that but my idea was a bit more experimental: why not make its background orange, its font black, the buttons black and their font white  :D Maybe that would add too much color/emphasis to that area... on the other hand I imagine it be more exciting than grey.
1. ![peermusic 0.2](https://cdn.pbrd.co/images/GdA8qOn.png)
2. ![grey playlist mockup](https://cdn.pbrd.co/images/GKp7sUn.jpg)
3. ![darker grey playlist mockup](https://cdn.pbrd.co/images/GKR3kGz.jpg)
4. ![orange playlist mockup](https://cdn.pbrd.co/images/GK6NHoo.jpg)

**Comment by queicherius** [comment]
Yeah, orange is **way** too much color imo. With the gray it would have a symmetry to the left side.

**Comment by perguth** [comment]
Short gut descision: same grey as in 3 or darker grey as in 4 (there I used the grey coming from the activated menu entries)?

**Comment by ryomiyaichi** [comment]
I would rather stick with one of the darker layouts. The orange puts way too much unnecessary emphasize on this area.

**Comment by queicherius** [comment]
I'd use the darker gray (activated menu items) - else the lines disappear.

**Comment by perguth** [comment]
:+1: for noting that, David.

To me all black looks very classy but also a bit loose having no border/distinction between those areas. So I would vote for 3.

**Comment by queicherius** [comment]
This is with the darker gray now.

**Comment by perguth** [comment]
:+1:
