### ISSUE TITLE
involvement documentation

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#78]
If you participated in some discussions, put forward some pull requests, etc.: It would be nice for me to have a short list of that in the end. I could use that when advertising our project in class.

**Comment by perguth** [comment]
Also for credits we could think a bit about the most helpful resources and list them on a special page in peermusic.

**Comment by queicherius** [comment]
I'm just gonna keep mine in a comment here and update it...

**Pull requests**
- https://github.com/creeperyang/id3-parser/pull/6 (merged)
- https://github.com/mikaelbr/gulp-notify/pull/105 (pending)

**Credits**
- http://www.flaticon.com/
- https://fortawesome.github.io/Font-Awesome/

**Comment by perguth** [comment]
# NPM modules written
1. [connect-instances](https://github.com/peermusic/connect-instances): A thin wrapper around `secure-webrtc-swarm`.
2. [file-system](https://github.com/peermusic/file-system): A slim wrapper around the Chrome filesystem API.
3. [in-memory-storage](https://github.com/peermusic/in-memory-storage):  A tiny module to store data in memory with a persistance layer using localStorage 
4. [music-metadata](https://github.com/peermusic/music-metadata): Parses music metadata from file name and ID3 tag.
5. [music-similarity](https://github.com/peermusic/music-similarity): Get similar artists for a given song by using a scraping server.
6. [node-scraping-server](https://github.com/peermusic/node-scraping-server): A small scraping server that performs tasks from authenticated users.
7. [player-engine](https://github.com/peermusic/player-engine): A slim wrapper around the HTML5 audio element.
8. [scrape-engine](https://github.com/peermusic/scrape-engine): A module for scraping Last.fm.
9. [secure-client-server-messaging](https://github.com/peermusic/secure-client-server-messaging): Easily encrypt/decrypt messages using the TweetNACL cryptographic library.
10. [secure-webrtc-swarm](https://github.com/peermusic/secure-webrtc-swarm): Create a swarm of authenticated p2p connections using webrtc and a signalhub.
11. [subfolders-too](https://github.com/peermusic/subfolders-too): Get _all_ files from a dropped directory.

**Comment by perguth** [comment]
Put it to use. See your inbox.
