### ISSUE TITLE
[1] Als Nutzer moechte ich die Wiedergabelaustaerke regeln koennen.

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#8]
... um eine gewuenschte Abspiellautstaerke einstellen zu koennen.
- [x] Lautstaerke-Regler anzeigen.
- [x] Lautstaerke-Regler bestimmt die Lautstaerke.

**Comment by Brotonyum** [comment]
Als Nutzer moechte ich die Wiedergabelautstaerke regeln koennen.

**Comment by perguth** [comment]
Implemented in https://github.com/peermusic/desktop
