### ISSUE TITLE
forward to https

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#82]
github.io offers valid certificates for all subdomains, so we can just use it.

**Comment by queicherius** [comment]
> Mixed Content: The page at '...' was loaded over HTTPS, but requested an insecure stylesheet '...'. This request has been blocked; the content must be served over HTTPS.

I just tried that. It would force users to run their signalhub server on https as well. Should we just keep it as it is at the moment?

**Comment by perguth** [comment]
Ah, yes then let's just put it back into the backlog.

**Comment by perguth** [comment]
We should force this when going live / maybe let gulp set a config flag for this, when deploying.

**Comment by queicherius** [comment]
I would honestly not force it. Especially for our demo we will probably not have a signalhub server running via SSL.

**Comment by perguth** [comment]
We already have :bowtie:

But maybe we want to demo setting up "our own signalhub server" live. Then we certainly wouldn't.

**Comment by perguth** [comment]
:+1:
