### ISSUE TITLE
copy to clipboard buttons

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#89]
- [ ] For all `web+peermusic` link fields like Github offers it for repo URLs.

**Comment by queicherius** [comment]
Github uses https://github.com/zeroclipboard/zeroclipboard. Sure we wanna include that (as in the files, bleh, flash) just for `CRTL+C`? I would be ok with just adding the native javascript api.

**Comment by perguth** [comment]
We just aim for Chrome anyway. If its works there :+1:
