### ISSUE TITLE
play indicator changes (SongRow)

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#90]
- [x] react also if hovering the title
- [x] when playing and hovered: show pause symbol and expose pause functionality

**Comment by queicherius** [comment]
> react also if hovering the title

I interpreted that as "also toggle play/pause when clicking the title". Also showing the pause symbol would need JS, because there are no [previous sibling selectors](http://stackoverflow.com/questions/1817792/is-there-a-previous-sibling-css-selector) in CSS.

**Comment by perguth** [comment]
Oh, I see.

We should write that bit of JS.

**Comment by perguth** [comment]
Nice! Feels much more natural now.
