### ISSUE TITLE
desktop notification on track change

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#91]
- [x] desktop notification (Artist, Track, Album, Cover Art)
- [x] enable/disable somewhere?

**Comment by queicherius** [comment]
Would you actually use that? I only have notifications enabled for mails and chat messages, having something pop up every 5 minutes would annoy me...

If you say you'd use it, it's an easy implementation.

**Comment by perguth** [comment]
In the beginning for sure - but I don't know if would be annoyed after a while too.

I wonder how it would be, if we could sneak controls in there (like "next" or "favorite").

**Comment by queicherius** [comment]
> I wonder how it would be, if we could sneak controls in there (like "next" or "favorite").

If I recall correctly the notifications only allow title, body and image. We'd need an extenstion to add buttons. :disappointed:
