### ISSUE TITLE
delete song directly / stop download directly

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#92]
**desktop**
- [x] disk symbol turns to delete x if hovered
- [x] the downloading spinner turns to x if hovered

**Comment by perguth** [comment]
:+1: I like the trash bin. But there is so little difference to the harddrive. What do you think about exchanging the harddrive with a CD (which to me still symbolizes "available and ready to play")?

**Comment by perguth** [comment]
When downloading: I would prefer a "x" shape. The trash bin tripped me of a bit there. Deleting/trashing implies having it first I would say.

**Comment by queicherius** [comment]
That better? :)

**Comment by perguth** [comment]
Yeah, thanks :)
