### ISSUE TITLE
Fully filled favicon

### ISSUE THREAD

**Issue by queicherius** [peermusic/user-stories#96]
Create a logo variant that is a fully filled square.

**Comment by queicherius** [comment]
@pguth 

Like this? 

![16](https://cloud.githubusercontent.com/assets/4615516/12495819/2a6781c6-c092-11e5-8131-69baec154656.png)
![path52201](https://cloud.githubusercontent.com/assets/4615516/12495804/176d02b2-c092-11e5-92f3-9ed72c4290df.png)
![200](https://cloud.githubusercontent.com/assets/4615516/12495803/176a8dd4-c092-11e5-92ed-af7e1759db22.png)

**Comment by perguth** [comment]
![logo light, transparent background](https://cdn.pbrd.co/images/YcZRBuK.png)

That as possible favicon competitor?

**Comment by queicherius** [comment]
I'd like the transparent one. Looks like a "super"program.

**Comment by queicherius** [comment]
peermusic/app@856ead1ddf02e40f588de1d051c554580f4ea91a

**Comment by perguth** [comment]
:+1:
