### ISSUE TITLE
have a few themes

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#98]
- [x] have 2-3 additional themes (maybe [Colourlovers: Palettes](http://www.colourlovers.com/palettes) comes in handy).
- [x] have a "Settings" menu entry below downloads under which there is a theme switcher

**Comment by queicherius** [comment]
We could do that pretty easily by just changing the scss colors variables and generating different styles. Would be fun, imo :+1:

**Comment by perguth** [comment]
My idea exactly!  :smile: I'll add some checkboxes...
